In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("deliveries.csv")
df.head(50)

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN
5,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,6,S Dhawan,DA Warner,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
6,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,7,S Dhawan,DA Warner,TS Mills,0,...,0,1,0,0,0,1,1,NaN,NaN,NaN
7,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,1,S Dhawan,DA Warner,A Choudhary,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
8,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,2,DA Warner,S Dhawan,A Choudhary,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
9,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,3,DA Warner,S Dhawan,A Choudhary,0,...,0,0,1,0,0,1,1,NaN,NaN,NaN
10,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,4,DA Warner,S Dhawan,A Choudhary,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
11,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,5,DA Warner,S Dhawan,A Choudhary,0,...,0,0,0,0,0,0,0,DA Warner,caught,Mandeep Singh
12,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,6,MC Henriques,S Dhawan,A Choudhary,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
13,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,7,MC Henriques,S Dhawan,A Choudhary,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
14,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,3,1,S Dhawan,MC Henriques,TS Mills,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
15,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,3,2,MC Henriques,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
16,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,3,3,MC Henriques,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
17,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,3,4,MC Henriques,S Dhawan,TS Mills,0,...,0,0,0,0,3,0,3,NaN,NaN,NaN
18,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,3,5,S Dhawan,MC Henriques,TS Mills,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
19,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,3,6,MC Henriques,S Dhawan,TS Mills,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
20,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,4,1,MC Henriques,S Dhawan,YS Chahal,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
21,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,4,2,MC Henriques,S Dhawan,YS Chahal,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
22,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,4,3,S Dhawan,MC Henriques,YS Chahal,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
23,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,4,4,S Dhawan,MC Henriques,YS Chahal,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
24,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,4,5,MC Henriques,S Dhawan,YS Chahal,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
25,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,4,6,S Dhawan,MC Henriques,YS Chahal,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
26,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,5,1,S Dhawan,MC Henriques,S Aravind,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
27,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,5,2,MC Henriques,S Dhawan,S Aravind,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
28,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,5,3,S Dhawan,MC Henriques,S Aravind,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
29,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,5,4,MC Henriques,S Dhawan,S Aravind,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
30,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,5,5,MC Henriques,S Dhawan,S Aravind,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
31,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,5,6,MC Henriques,S Dhawan,S Aravind,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
32,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,6,1,S Dhawan,MC Henriques,SR Watson,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
33,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,6,2,S Dhawan,MC Henriques,SR Watson,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
34,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,6,3,S Dhawan,MC Henriques,SR Watson,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
35,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,6,4,S Dhawan,MC Henriques,SR Watson,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
36,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,6,5,S Dhawan,MC Henriques,SR Watson,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
37,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,6,6,S Dhawan,MC Henriques,SR Watson,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
38,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,7,1,S Dhawan,MC Henriques,YS Chahal,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
39,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,7,2,MC Henriques,S Dhawan,YS Chahal,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
40,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,7,3,MC Henriques,S Dhawan,YS Chahal,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
41,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,7,4,S Dhawan,MC Henriques,YS Chahal,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
42,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,7,5,MC Henriques,S Dhawan,YS Chahal,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
43,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,7,6,S Dhawan,MC Henriques,YS Chahal,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
44,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,8,1,S Dhawan,MC Henriques,TM Head,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
45,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,8,2,MC Henriques,S Dhawan,TM Head,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
46,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,8,3,S Dhawan,MC Henriques,TM Head,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
47,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,8,4,MC Henriques,S Dhawan,TM Head,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
48,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,8,5,MC Henriques,S Dhawan,TM Head,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
49,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,8,6,S Dhawan,MC Henriques,TM Head,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN

### top 5 batsman in terms of runs scored

In [3]:
players = df.groupby('batsman')

In [4]:
players.first().shape

(461, 20)

In [5]:
players['batsman_runs'].sum()

batsman
A Ashish Reddy     280
A Chandila           4
A Chopra            53
A Choudhary         25
A Flintoff          62
                  ...
YV Takawale        192
Yashpal Singh       47
Younis Khan          3
Yuvraj Singh      2591
Z Khan             117
Name: batsman_runs, Length: 461, dtype: int64

In [6]:
players['batsman_runs'].sum().sort_values(ascending=False).head()

batsman
SK Raina     4548
V Kohli      4423
RG Sharma    4207
G Gambhir    4132
DA Warner    4014
Name: batsman_runs, dtype: int64

### to findout the batsman who hit more 4's or 6's|

In [7]:
mask = df['batsman_runs']==6
f_king = df[mask]
f_king

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
10,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,4,DA Warner,S Dhawan,A Choudhary,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
47,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,8,4,MC Henriques,S Dhawan,TM Head,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
75,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,13,2,Yuvraj Singh,MC Henriques,A Choudhary,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
89,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,15,3,Yuvraj Singh,MC Henriques,S Aravind,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
91,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,15,5,MC Henriques,Yuvraj Singh,S Aravind,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150395,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,10,2,V Kohli,CH Gayle,Mustafizur Rahman,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
150413,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,13,2,V Kohli,AB de Villiers,BB Sran,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
150428,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,15,5,SR Watson,KL Rahul,MC Henriques,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
150440,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,17,5,STR Binny,Sachin Baby,Mustafizur Rahman,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
150453,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,19,6,Sachin Baby,CJ Jordan,Mustafizur Rahman,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN

#### no:of 4's till date

In [8]:
f_king.shape[0]

6523

In [9]:
f_king.groupby('batsman').size().sort_values(ascending=False).head()

batsman
CH Gayle     266
SK Raina     174
RG Sharma    173
V Kohli      160
DA Warner    160
dtype: int64

In [10]:
f_king.groupby('batsman')['batsman_runs'].count().sort_values(ascending=False).head()

batsman
CH Gayle     266
SK Raina     174
RG Sharma    173
V Kohli      160
DA Warner    160
Name: batsman_runs, dtype: int64

### on which 3 teams virat kohli scored more runs

In [11]:
mask1 = df['batsman'] == 'V Kohli'
vk = df[mask1]

In [12]:
vk.groupby('bowling_team')['batsman_runs'].sum().sort_values(ascending=False).head()

bowling_team
Chennai Super Kings    706
Delhi Daredevils       661
Kings XI Punjab        483
Mumbai Indians         447
Sunrisers Hyderabad    439
Name: batsman_runs, dtype: int64

### seperately creating a function